pipeline:
  name: harness-github
  identifier: harnessgithub
  projectIdentifier: Infra
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: trivy_docker_image
        build: <+input>
  stages:
    - stage:
        name: imagebuild
        identifier: imagebuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.danfstatestcluster
              namespace: harness-delegate-ng-statest
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: terraform
                  identifier: terraform
                  spec:
                    connectorRef: ravidockergithub
                    repo: rs2k/terraform
                    tags:
                      - v1.0
                  failureStrategies: []
              - step:
                  identifier: trivy
                  name: Run Trivy vulnerability scanner
                  type: Plugin
                  spec:
                    connectorRef: ravidockergithub
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: aquasecurity/trivy-action@master
                      with:
                        image-ref: drone/git
                        format: table
                        exit-code: "1"
                        ignore-unfixed: "true"
                        vuln-type: os,library
                        severity: HIGH,LOW
                      env:
                        CI: true
                  failureStrategies: []
